-- Explore All Object in the DB
SELECT * FROM INFORMATION_SCHEMA."TABLES"

-- Explore All Columns in the DB
SELECT * FROM INFORMATION_SCHEMA."COLUMNS"

SELECT *
FROM INFORMATION_SCHEMA."COLUMNS"
WHERE
    TABLE_NAME = 'dim_customers'